name: update-leaderboard

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install C++ dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Configure CMake
      run: cmake -B build

    - name: Build project
      run: cmake --build build

    - name: Run sorting tests
      run: |
        mkdir -p results
        ./build/run github_runner_1
        ./build/run github_runner_2
        ./build/run github_runner_3
        echo "Generated files:"
        ls -l results/

    - name: Install Python dependencies
      run: pip install matplotlib numpy python-dateutil tabulate

    - name: Generate leaderboard
      run: python3 leaderboard.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Update leaderboard $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
